# Generated by Django 4.2.5 on 2024-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0007_alter_studentresult_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='file',
            field=models.FileField(blank=True, upload_to='result_sheets'),
        ),
    ]
